update: nl -> eng
YouriLieverdink/MonetarySystem pull request #65
Opened 2021-11-17 12:22 UTC by JasperSikkema

translated the remaining dutch parts of the document

2021-11-17 12:25 UTC, JasperSikkema commented
branch name is wrong its about the acceptation document

2021-11-17 12:36 UTC, JasperSikkema commented
also added chapter 2 responsiblities

2021-11-17 16:05 UTC, YouriLieverdink requested changes
A small amount of spelling mistakes.

2021-11-17 16:05 UTC, YouriLieverdink commented on docs/acceptation_plan.md
> +### 1.2 Refrences
References

2021-11-17 16:05 UTC, YouriLieverdink commented on docs/acceptation_plan.md
> +| Teacher | The teacher checks if the documents are complete and contain the right information |
Missing a `.`.

2021-11-17 16:05 UTC, YouriLieverdink commented on docs/acceptation_plan.md
> +The Reliability of the data itself will come with the size of the blockchain. A transaction is accepted when more than 50 percent agrees that the transaction is valid. When the blockchain has a rease
Reasonable

2021-11-18 09:29 UTC, YouriLieverdink approved these changes

2021-11-18 09:29 UTC, merged